env:
  IMAGE_NAME: "${{ github.repository }}"
  REGISTRY: ghcr.io
name: Build and publish docker image
'on':
  push:
    branches:
    - main
jobs:
  build-and-push:
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      
    - name: Login to container repo
      uses: docker/login-action@v3
      with:
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: "${{ env.REGISTRY }}"
        username: "${{ github.actor }}"

    - id: meta
      name: Extract metadata for Publish
      uses: docker/metadata-action@v5
      with:
        images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

    - id: push
      name: Build and Push Image
      uses: docker/build-push-action@v6
      with:
        context: "."
        labels: "${{ steps.meta.outputs.labels }}"
        push: true
        tags: "${{ steps.meta.outputs.tags }}"
        
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        push-to-registry: true
        subject-digest: "${{ steps.push.outputs.digest }}"
        subject-name: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
